enableInlineHunks: true

enableMessageNames: false

initScope: peacockproject

nodeLinker: node-modules

packageExtensions:
    express@*:
        dependencies:
            mime: "npm:1.6.0"

plugins:
    -   path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
        spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-4.0.0-rc.26.cjs
