enableGlobalCache: false

enableInlineHunks: true

enableMessageNames: false

initScope: peacockproject

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-4.0.0-rc.40.cjs
