blank_issues_enabled: true
contact_links:
  - name: Discord Support
    url: https://thepeacockproject.org/discord
    about: Our Discord has a channel dedicated for getting any help you need with the setup or operation of Peacock.

