name: Localisation

on:
  push:
    branches: ["master"]
    paths: ["resources/locale.json", ".github/workflows/locale.yml"]
  workflow_dispatch:

jobs:
  rebuild-locale:
    name: Rebuild Localisation
    runs-on: windows-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Peacock
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.PEACOCKBOT_TOKEN }}
          path: "./Peacock"

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.0.0
        with:
          node-version-file: "./Peacock/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "./Peacock/yarn.lock"

      - name: Install Packages
        run: |
          cd Peacock
          yarn install --immutable

      - name: Download RPKG-CLI
        id: rpkgcli
        uses: step-security/release-downloader@97a991ef6b59ac73abb83e8e4b70a73118d27d44 # v1.12.0
        with:
          repository: "glacier-modding/RPKG-Tool"
          latest: true
          fileName: "rpkg_*-cli.zip"
          out-file-path: "Peacock/resources"

      - name: Download HMLanguageTools
        id: hmlt
        uses: step-security/release-downloader@97a991ef6b59ac73abb83e8e4b70a73118d27d44 # v1.12.0
        with:
          repository: "AnthonyFuller/TonyTools"
          latest: true
          fileName: "TonyTools.zip"
          out-file-path: "Peacock/resources"

      - name: Unzip dependencies
        run: |
          cd Peacock/resources
          7z x ${{ fromJson(steps.rpkgcli.outputs.downloaded_files)[0] }}
          7z x ${{ fromJson(steps.hmlt.outputs.downloaded_files)[0] }}

      - name: Rebuild Locale Packages
        run: |
          cd Peacock
          yarn rebuild-locale

      - name: Push updated RPKG files
        uses: step-security/add-and-commit@6b975a6ae39f11794750730d8846a1d2e84699ba # v10.0.0
        with:
          cwd: "./Peacock"
          add: |
            resources/dynamic_resources_h2.rpkg
            resources/dynamic_resources_h3.rpkg
          author_name: PeacockBot
          author_email: admin@thepeacockproject.org
          message: "[skip ci] Update locale packages"
