name: Update Localisation Mod

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  update-mod:
    name: Update Mod
    runs-on: windows-latest

    steps:
      - name: Checkout Peacock
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          token: ${{ secrets.PEACOCKBOT_TOKEN }}
          path: "./Peacock"

      - name: Checkout Peacock Strings
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.PEACOCKBOT_TOKEN }}
          repository: thepeacockproject/peacock-strings
          path: "./PeacockStrings"

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.0.0
        with:
          node-version-file: "./Peacock/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "./Peacock/yarn.lock"

      - name: Install Packages
        run: |
          cd Peacock
          yarn install --immutable

      - name: Download RPKG-CLI
        id: rpkgcli
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          repository: "glacier-modding/RPKG-Tool"
          latest: true
          fileName: "rpkg_*-cli.zip"
          out-file-path: "Peacock/resources"

      - name: Download HMLanguageTools
        id: hmlt
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          repository: "AnthonyFuller/TonyTools"
          latest: true
          fileName: "TonyTools.zip"
          out-file-path: "Peacock/resources"

      - name: Unzip dependencies
        run: |
          cd Peacock/resources
          7z x ${{ fromJson(steps.rpkgcli.outputs.downloaded_files)[0] }}
          7z x ${{ fromJson(steps.hmlt.outputs.downloaded_files)[0] }}

      - name: Rebuild Locale Packages
        run: |
          cd Peacock
          yarn rebuild-locale

      - name: Copy peacockstrings.locr.json
        run: |
          copy ./Peacock/resources/peacockstrings.locr.json ./PeacockStrings/content/chunk0/peacockstrings.locr.json

      - name: Push updated Peacock LOCR
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          cwd: "./PeacockStrings"
          add: content/chunk0/peacockstrings.locr.json
          author_name: PeacockBot
          author_email: admin@thepeacockproject.org
          message: "enhancement: update strings"
