name: Patcher

on:
  push:
    branches: [ "v*", "master" ]
    paths: [ "patcher/**/*" ]
  pull_request:
    branches: [ "v*", "master" ]
    paths: [ "patcher/**/*" ]

env:
  DOTNET_VERSION: 8.x

permissions:
  contents: read

jobs:
  build:
    name: Build Patcher
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Patcher
        run: |
          export DOTNET_NOLOGO=true
          export DOTNET_CLI_TELEMETRY_OPTOUT=true
          cd patcher
          dotnet publish HitmanPatcher/HitmanPatcher.csproj -c Release -p DebugType=none -o Publish/Windows

      - name: Upload patcher-windows
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.0
        with:
          name: patcher-windows
          path: patcher/Publish/Windows/ILRepack
