name: Patcher - Publish

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for Git to git push
    name: Publish Patcher
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref_name }}
          path: repository

      - name: Download patcher-windows
        run: |
          cd repository
          RUN_ID=$(gh run list --workflow="patcher.yml" --branch=master --limit=1 --json databaseId,status,conclusion -q 'map(select(.status == "completed" and .conclusion == "success")) | .[0].databaseId')

          if [ -z "$RUN_ID" ]; then
            echo "No run ID found"
            exit 0
          fi

          gh run download $RUN_ID -n patcher-windows -D ../patcher-windows

          if [ $? -ne 0 ]; then
            echo "Failed to download patcher-windows"
            exit 0
          fi

      - name: Copy patcher-windows to repository
        run: |
          cp -f patcher-windows/PeacockPatcher.exe repository/PeacockPatcher.exe

      - name: Commit and push to repository
        run: |
          cd repository
          git config user.name "PeacockBot"
          git config user.email "admin@thepeacockproject.org"
          git add PeacockPatcher.exe
          git commit -m "[skip ci] Update patcher binary"
          git push
